---
title: "Fig2_cell proportion"
author: "Qiuyun Yang"
date: "`r Sys.Date()`"
output: html_document
---
#cell proportion

my7colors <- c( '#58A4C3',  '#AA9A59', '#E63863', '#E39A35', '#6778AE', '#91D0BE', '#B53E2B','#712820', '#DCC1DD', '#CCE0F5', '#CCC9E6', '#625D9E', '#68A180', '#3A6963','#968175')

x=immune.combined.sct@meta.data$celltype
table(x)
pB2_df <- table(immune.combined.sct@meta.data$celltype,immune.combined.sct@meta.data$orig.ident) %>% melt()
colnames(pB2_df) <- c("Cluster","Sample","Number")
cluster=c("Neuron","Oligodendrocyte","Astrocyte & NSC","Microglia","OPC","Endocelia","Ependymal")
pB2_df$Cluster <- factor(pB2_df$Cluster,levels = cluster)

groupcolor <- c("#BC3C29","#0072B5","#E18727","#20854E","#7876B1","#6F99AD","#FFDC91")
sample_color <- groupcolor

pB3 <- ggplot(data = pB2_df, aes(x =Number, y = Cluster , fill = Sample)) +
  geom_bar(stat = "identity", width=0.8,position="fill")+
  scale_fill_manual(values=sample_color) +
  theme_bw()+
  theme(panel.grid =element_blank()) +
  labs(x="",y="Ratio")+

  theme(axis.text.y = element_text(size=12, colour = "black"))+
  theme(axis.text.x = element_text(size=12, colour = "black"))
pB3

sample_color <- my7colors
pB4 <- ggplot(data = pB2_df, aes(x =Number, y = Sample, fill =  Cluster)) +
  geom_bar(stat = "identity", width=0.8,position="fill")+
  scale_fill_manual(values=sample_color) +
  theme_bw()+
  theme(panel.grid =element_blank()) +
  labs(x="",y="Ratio")+

  theme(axis.text.y = element_text(size=12, colour = "black"))+
  theme(axis.text.x = element_text(size=12, colour = "black"))
pB4
