---
title: "Fig2_GSVA"
author: "Qiuyun Yang"
date: "`r Sys.Date()`"
output: html_document
---

##GSVA
library(GSEABase)
library(clusterProfiler)
##  devtools::install_github("GSEA-MSigDB/GSEA_R")
library(GSEA)
library(GSVA)
library(msigdbr)
kegggmt2 <- read.gmt("c2.cp.kegg.v7.4.symbols.gmt")

kegg_list = split(kegggmt2$gene, kegggmt2$term)
#?AverageExpression
x=AverageExpression(immune.combined.sct)

exp=x[["RNA"]]
exp1=as.matrix(exp)

m_df<- msigdbr(species = "Mus musculus",  category = "C2", subcategory = "KEGG")
fgsea_sets<- m_df %>% split(x = .$gene_symbol, f = .$gs_name)

es.max <- gsva(exp1, fgsea_sets, mx.diff=FALSE)
#?gsva
pheatmap::pheatmap(es.max, 
                   cluster_rows = T,
                   cluster_cols =T,
                   show_colnames=T,
                   scale = "row", 
                   color =colorRampPalette(c("#FF7744", "white","#AAAAAA","#0044BB"))(100),
                   breaks = seq(-2,2,length.out = 100),
                   cellwidth = 15,cellheight = 12,fontsize = 8,
                   filename ="GSVA.pdf")

colnames(immune.combined.sct@meta.data)
cell.type=AverageExpression(immune.combined.sct,add.ident = "orig.ident")
cell.type=cell.type[[1]]
cell.type=as.matrix(cell.type)

es.max1 <- gsva(cell.type, fgsea_sets, mx.diff=FALSE)

pheatmap::pheatmap(es.max1, 
                   cluster_rows = F,
                   cluster_cols =F,
                   show_colnames=T,
                   scale = "row", #以行来标准化，这个功能很不错
                   #color =colorRampPalette(c("#FF7744", "white","#AAAAAA","#0044BB"))(100),
                   breaks = seq(-2,2,length.out = 100),
                   cellwidth = 15,cellheight = 12,fontsize = 8,
                   filename ="GSVA-celltype.pdf")
