---
title: "Fig3_Visual_cell_communication_pathways"
author: "Qiuyun Yang"
date: "`r Sys.Date()`"
output: html_document
---

library(CellChat)
library(tidyverse)
library(ggalluvial)
library(Seurat)
library(data.table)
library(ggsci)

#Visual cell communication
pathways.show <- c("OPIOID") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("BMP") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("CSF") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("PSAP") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("WNT") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("VISFATIN") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("TGFb") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("FGF") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("VEGF") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

pathways.show <- c("ACTIVIN") 
weight.max <- getMaxWeight(cc.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(cc.list)) {
  netVisual_aggregate(cc.list[[i]], signaling = pathways.show, layout = "chord", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(cc.list)[i]))
}

