---
title: "Fig4_cell proportion"
author: "Qiuyun Yang"
date: "`r Sys.Date()`"
output: html_document
---
###################################################################################
##cell proportion
library(Seurat)
library(ggplot2)
library(dplyr)
library(ggalluvial)

Ratio <- immune.combined.sct@meta.data %>% 
  group_by(orig.ident,celltype) %>% 
  summarise(n=n()) %>%
  mutate(relative_freq = n/sum(n)) 

ggplot(Ratio, aes(x =orig.ident, y= relative_freq, fill = celltype,
                  stratum=celltype, alluvium=celltype)) +
  stat_boxplot (geom= "errorbar", width = 0.2, lwd = 1,colour = my36colors) +
  geom_boxplot (width = 0.3, lwd = 1,colour = my36colors)+
  geom_col(width = 0.5, color='black')+
  geom_flow(width=0.5,alpha=0.4, knot.pos=0.5)+ 
  theme_classic() +
  labs(x='Sample',y = 'Ratio')+
  coord_flip()+
  scale_fill_manual(values = my7colors)

x=immune.combined.sct@meta.data$celltype
table(x)
pB2_df <- table(immune.combined.sct@meta.data$celltype,immune.combined.sct@meta.data$orig.ident) %>% melt()
colnames(pB2_df) <- c("Cluster","Sample","Number")
table(immune.combined.sct@meta.data$celltype)
cluster=c("Astrocytes","qNSC","early aNSC","late aNSCs","Neuroblasts")
pB2_df$Cluster <- factor(pB2_df$Cluster,levels = cluster)

groupcolor <- c("#BC3C29","#0072B5","#E18727","#20854E","#7876B1","#6F99AD","#FFDC91")
sample_color <- groupcolor

pB3 <- ggplot(data = pB2_df, aes(x =Number, y = Cluster , fill = Sample)) +
  geom_bar(stat = "identity", width=0.8,position="fill")+
  scale_fill_manual(values=sample_color) +
  theme_bw()+
  theme(panel.grid =element_blank()) +
  labs(x="",y="Ratio")+
  theme(axis.text.y = element_text(size=12, colour = "black"))+
  theme(axis.text.x = element_text(size=12, colour = "black"))
pB3
