---
title: "Fig5_GO analysis"
author: "Qiuyun Yang"
date: "`r Sys.Date()`"
output: html_document
---

#Differentially expressed genes
tmp1$ph_res
dev.off()
gene_group=tmp1$annotation_row 
gene_group$gene=rownames(gene_group)
write.csv(gene_group, file = "pseudotime_gene_group.csv")

genes <- row.names(subset(fData(HSMM),gene_short_name %in% c("Prex2","Maml3","Nrxn3","Erbb4","Csmd1","Adamts18","Wdr17","Fars2","Tcf7l1","Phkg1")))
p1=plot_genes_branched_pseudotime(HSMM[genes,],
                                  branch_point = 2,
                                  cell_size=2,
                                  ncol = 1)
p1
# GO analysis
library(clusterProfiler) 
library(org.Mm.eg.db) 

allcluster_go=data.frame() 
for (i in unique(gene_group$Cluster)) {   
  small_gene_group=filter(gene_group,gene_group$Cluster==i)
  df_name=bitr(small_gene_group$gene, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")
  go <- enrichGO(gene         = unique(df_name$ENTREZID),
                 OrgDb         = "org.Mm.eg.db", 
                 keyType       = 'ENTREZID',
                 ont           = "BP",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.01, 
                 qvalueCutoff  = 0.05,
                 readable      = TRUE)
  go_res=go@result
  if (dim(go_res)[1] != 0) {
    go_res$cluster=i
    allcluster_go=rbind(allcluster_go,go_res)
  }
}
#head(allcluster_go[,c("ID","Description","qvalue","cluster")])

write.csv(allcluster_go,'enrichGO_allcluster_go.csv') 

dev.off()